name: ai_trade
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.4
  dio: ^5.4.3+1
  lottie: ^3.1.2
  dartz: ^0.10.1
  get_it: ^7.7.0
  skeletons: ^0.0.3
  equatable: ^2.0.5
  go_router: ^14.2.0
  slide_to_act: ^2.0.2
  url_strategy: ^0.2.0
  flutter_bloc: ^8.1.6
  gradient_borders: ^1.0.1
  shared_preferences: ^2.2.3
  simple_gradient_text: ^1.3.0
  google_generative_ai: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: PoppinsMed
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: PoppinsLig
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
    - family: PoppinsReg
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
